#include "../include/templates.h"

const char* main_c_template =
    "#include <stdio.h>\n"
    "\n"
    "int main(void) {\n"
    "    printf(\"Hello, {{project_name}}!\\n\");\n"
    "    return 0;\n"
    "}\n";

const char* readme_template =
    "# {{project_name}}\n"
    "\n"
    "A new C project initialized by genc.\n";

const char* gitignore_template =
    "target/\n"
    "*.o\n"
    "*.exe\n";

const char* genc_toml_template =
    "[package]\n"
    "name = \"{{project_name}}\"\n"
    "version = \"0.1.0\"\n"
    "edition = \"2026\"\n"
    "compliler = \"gcc\" # use g++ or your compliler of choice\n"
    "\n"
    "[build]\n"
    "src_dir = \"src/main.c\"\n"
    "include_dir = \"include/\"\n"
    "bin_dir = \"bin/\"\n"
    "\n"
    "[dependencies]\n"
    "# library_name = { url = \"segfault/genc\", version = \"*\" }\n"
    "\n";

const char* genc_clang_format_template =
    "Language: C\n"
    "BasedOnStyle: LLVM\n"
    "\n"
    "# ==================================================\n"
    "# Braces style (Allman / school style)\n"
    "# ==================================================\n"
    "BreakBeforeBraces: Allman\n"
    "\n"
    "# ==================================================\n"
    "# Indentation (4 spaces, NO tabs)\n"
    "# ==================================================\n"
    "IndentWidth: 4\n"
    "TabWidth: 4\n"
    "UseTab: Never\n"
    "\n"
    "# ==================================================\n"
    "# Line length\n"
    "# ==================================================\n"
    "ColumnLimit: 0\n"
    "\n"
    "# ==================================================\n"
    "# Alignment\n"
    "# ==================================================\n"
    "AlignConsecutiveDeclarations: true\n"
    "AlignConsecutiveAssignments: false\n"
    "AlignAfterOpenBracket: Align\n"
    "\n"
    "# ==================================================\n"
    "# One-statement-per-line discipline\n"
    "# ==================================================\n"
    "AllowShortFunctionsOnASingleLine: None\n"
    "AllowShortIfStatementsOnASingleLine: Never\n"
    "AllowShortLoopsOnASingleLine: false\n"
    "\n"
    "# ==================================================\n"
    "# Spacing rules\n"
    "# ==================================================\n"
    "PointerAlignment: Left\n"
    "SpaceBeforeParens: ControlStatements\n"
    "\n"
    "# ==================================================\n"
    "# Keep tables & initializer lists stable\n"
    "# ==================================================\n"
    "BinPackArguments: true\n"
    "BinPackParameters: true\n"
    "Cpp11BracedListStyle: true\n"
    "\n"
    "# ==================================================\n"
    "# Comments\n"
    "# ==================================================\n"
    "ReflowComments: true\n"
    "SpacesBeforeTrailingComments: \n";
